### ISSUE TITLE
Not safe to have multiple Lua states in different threads / tasks?

### ISSUE THREAD

**Issue by DavidR91** [NLua/NLua#198]
I am receiving intermittent NullReferenceExceptions when doing code such as the following:

```
class Program
{
    private static void Script(string script)
    {
        using (Lua l = new Lua())
        {
            l.LoadCLRPackage();
            l.DoFile(script);
        }
    }

    public static void Main(string[] args)
    {
        Task.WaitAll(
            Task.Run(() =>
            {
                Script("A.lua");
            }),
            Task.Run(() =>
            {
                Script("B.lua");
            }),
            Task.Run(() =>
            {
                Script("C.lua");
            }));
    }
}
```

The full stacktrace is as follows:

```
        Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
           at NLua.ObjectTranslator.LoadAssembly(LuaState luaState)
           at KeraLua.NativeMethods.LuaNetPCall(IntPtr luaState, Int32 nArgs, Int32 nResults, Int32 errfunc)
           at NLua.LuaLib.LuaLDoString(LuaState luaState, String chunk)
           at NLua.Lua.Init()
           at NLua.Lua..ctor()
           at .Program.Script(String script) in \Program.cs:line 14
           at .Program.<>c.<Main>b__1_0() in\Program.cs:line 24
           at System.Threading.Tasks.Task.InnerInvoke()
           at System.Threading.Tasks.Task.Execute()
           --- End of inner exception stack trace ---
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
           at .Program.Main(String[] args) in \Program.cs:line 21
```

Am I correct in assuming that there is some kind of shared state which means, even when instancing separate `Lua`s, it is never safe to operate them on separate threads/tasks simultaneously? 

Note that the behaviour (and stacktrace) is the same if you just _instance_ Lua - it is not necessary to load CLR packages or actually call DoFile

**Comment by AntonNep** [comment]
@DavidR91, have you tried using a version containing NLua concurrency fix (#196)?
