### ISSUE TITLE
After upgrading, my script fails to run

### ISSUE THREAD

**Issue by UweKeim** [NLua/NLua#273]
A script, several years old and working, suddenly stopped working after upgrading to the latest NLua/KeraLua.

A repro for the error is:

```csharp
namespace NLuaTest01
{
    using NLua;
    using System;
    using System.Linq;

    internal static class Program
    {
        private static int Main(string[] args)
        {
            try
            {
                const string script = @"r = system:run(""C:\\Windows\\notepad.exe"");";

                var lua = new Lua
                {
                    [@"system"] = new ExecutionApiSystemScriptObject(),
                };

                var result = lua.DoString(script)?.FirstOrDefault();
                Console.WriteLine(result);

                return 0;
            }
            catch (Exception x)
            {
                Console.Error.WriteLine(x.ToString());
                return -1;
            }
        }
    }

    public sealed class ExecutionApiSystemScriptObject
    {
        public void run(
            string commandLine,
            int successReturnCode = 0,
            int retryCount = 0,
            string logMode = null,
            bool waitForExit = true)
        {
            // Would do something here.
        }
    }
}
```

The error thrown is:

> NLua.Exceptions.LuaScriptException: [string "chunk"]:1: Invalid arguments to method: ExecutionApiSystemScriptObject.run

With a call stack:

```txt
at NLua.Lua.ThrowExceptionFromError(Int32 oldTop)
at NLua.Lua.DoString(String chunk, String chunkName)
at NLuaTest01.Program.Main(String[] args) in C:\MyTest\Program.cs:Zeile 20.
```

**My question:**

What am I doing wrong here?

**Comment by UweKeim** [comment]
The error disappears, if I remove this line from the above code:

```csharp
string logMode = null,
```

So it seems that default string parameters are handled differently in newer versions of NLua.

Any hint on this?

**Comment by viniciusjarina** [comment]
This could be a regression not covered by the tests. :cry
I will take a look later

**Comment by UweKeim** [comment]
That works perfectly. Thanks a million times for you quick help, Vinicius.

**Comment by viniciusjarina** [comment]
I thank you for the 🐜 report.
