### ISSUE TITLE
liblua54.so not found on linux arm and arm64

### ISSUE THREAD

**Issue by chenxuuu** [NLua/NLua#400]
I'm trying to use this on .net 5 ,it seems no `liblua54.so` in path `Debug\net5.0\runtimes\linux-arm\native` and `Debug\net5.0\runtimes\linux-arm64\native`. when I run it on aarch64 GNU/Linux I got an error

is it possible to support arm?

and , I tried to compile `https://github.com/NLua/lua.git` and copy `liblua54.so` to target folder, it also throw an error

**Comment by viniciusjarina** [comment]
Hi @chenxuuu in theory building an `aarch64` should be enough.

If you want to add instructions to cross-compile to aarch64 on Azure DevOps feel free to do it, I will happy to merge it

**Comment by chenxuuu** [comment]
I built lua([repo](https://github.com/NLua/lua.git)) on that machine and moved liblua54.so to it's folder, it can run lua but behavior is very strange
such as abort with `import("System")`

```lua
print(11111111)
print(2222)
import("System")
print(DateTime.Now.Ticks)
print("end")
```

```bash
──> ./test
11111111
2222
[1]    3694 abort      ./test
```

I have no idea🤔

**Comment by viniciusjarina** [comment]
Try to run tests and see what you get. I don't have a arm64 device to try :/

**Comment by chenxuuu** [comment]
> 
> 
> I built lua([repo](https://github.com/NLua/lua.git)) on that machine and moved liblua54.so to it's folder, it can run lua but behavior is very strange
> such as abort with `import("System")`
> 
> ```lua
> print(11111111)
> print(2222)
> import("System")
> print(DateTime.Now.Ticks)
> print("end")
> ```
> 
> ```shell
> ──> ./test
> 11111111
> 2222
> [1]    3694 abort      ./test
> ```
> 
> I have no idea🤔

maybe this is another bug, I'll test this

**Comment by viniciusjarina** [comment]
Try to run `KeraLua` tests
  - nuget restore KeraLua.sln
  - msbuild KeraLua.sln /p:Configuration=Release /t:Restore
  - msbuild KeraLua.sln /p:Configuration=Release
  - dotnet test ./tests/build/net45/bin/Release/KeraLuaTest.dll

https://github.com/NLua/KeraLua/blob/master/.travis.yml#L19

**Comment by dcleyne** [comment]
Trying to get this running in dotnet core on Raspberry Pi.

When running the tests I get:

`
lua/test $ ../install/bin/lua all.lua

        Starting Tests
random seeds: 1669504626, 29307220
current path:
****/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua****

    ---- total memory: 36.9K, max memory: 36.9K ----

time: 0.000142 (+0.000142)

***** FILE 'main.lua'*****
testing stand-alone interpreter
progname: ../install/bin/lua
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
(temporary program file used in these tests: /tmp/lua_ezDFqI)
testing warnings
../install/bin/lua: main.lua:343: assertion failed!
stack traceback:
        [C]: in function 'assert'
        main.lua:343: in main chunk
        (...tail calls...)
        all.lua:155: in main chunk
        [C]: in ?
`

**Comment by MRIIOT** [comment]
I am revisiting this.  So far it appears that KeraLua on linux-arm64 passes all tests.


```
cd ~
wget https://dot.net/v1/dotnet-install.sh
bash ./dotnet-install.sh --channel 8.0
export PATH="$HOME/.dotnet/:$PATH"
dotnet --version

git clone https://github.com/NLua/KeraLua
cd KeraLua
git submodule update --init --recursive
# comment signing from build/net8.0/KeraLua.net.8.0.csproj
dotnet restore KeraLua.net8.0.sln
dotnet publish -c Release -r linux-arm64 -o out -verbosity:diag --self-contained true KeraLua.net8.0.sln

dotnet test out/KeraLuaTest.net8.0.dll
# Passed!  - Failed:     0, Passed:    24, Skipped:     0, Total:    24, Duration: 8 s - KeraLuaTest.net8.0.dll (net8.0)
```

**Comment by chenxuuu** [comment]
still have this probrem, only failed on linux arm

https://github.com/chenxuuu/llcom/actions/runs/14185123479

```log
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Basic [24 ms]
  Error Message:
   Test method llcomTest.Lua.Basic threw exception: 
System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/lua54.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.14/lua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/lua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/liblua54.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.14/liblua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/liblua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/lua54: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.14/lua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/lua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/liblua54: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.14/liblua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/liblua54: cannot open shared object file: No such file or directory

  Stack Trace:
      at KeraLua.NativeMethods.luaL_newstate()
   at KeraLua.Lua..ctor(Boolean openLibs)
   at NLua.Lua..ctor(Boolean openLibs)
   at llcomTest.Lua.Basic() in /home/runner/work/llcom/llcom/llcomNext/llcomTest/Lua.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:    15, Skipped:     0, Total:    16, Duration: 308 ms - llcomTest.dll (net8.0)
```

**Comment by viniciusjarina** [comment]
KeraLua 1.4.4 should include arm64 arch. 
But there is a problem when you have native dependencies using .NET. If you use AnyCPU and build and pack your app on x64 the .targets of KeraLua will most likely copy the x64 version (this will happen on Linux or Windows).
macOS don't have this issue since they have fat binary. 
Ideally if you want to be sure you will run on each different arch I would do two different build configurations x64 and ARM64 then you can build and pack and the .targets will copy the correct .dll/.so

**Comment by chenxuuu** [comment]
it works perfect now

**Comment by chenxuuu** [comment]
arm64 native library missing again in NLua 1.7.6  :-|

[GitHub Action Test Log](https://github.com/chenxuuu/llcom/actions/runs/21052471556/job/60541610455)
```
  llcomTest -> /home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/llcomTest.dll
Test run for /home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/llcomTest.dll (.NETCoreApp,Version=v8.0)
VSTest version 18.0.1 (arm64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Basic [8 ms]
  Error Message:
   Test method llcomTest.Lua.Basic threw exception:
System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/lua54.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.23/lua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/lua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/liblua54.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.23/liblua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/liblua54.so: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/lua54: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.23/lua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/lua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/runtimes/linux-arm64/native/liblua54: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.23/liblua54: cannot open shared object file: No such file or directory
/home/runner/work/llcom/llcom/llcomNext/llcomTest/bin/Debug/net8.0/liblua54: cannot open shared object file: No such file or directory

  Stack Trace:
     at KeraLua.NativeMethods.luaL_newstate()
   at KeraLua.Lua..ctor(Boolean openLibs)
   at NLua.Lua..ctor(Boolean openLibs)
   at llcomTest.Lua.Basic() in /home/runner/work/llcom/llcom/llcomNext/llcomTest/Lua.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:    23, Skipped:     0, Total:    24, Duration: 717 ms - llcomTest.dll (net8.0)
Error: Process completed with exit code 1.
```

**Comment by viniciusjarina** [comment]
It should work now https://github.com/NLua/NLua/releases/tag/v1.7.8

**Comment by chenxuuu** [comment]
It works
maybe should add a ci test for this?
