### ISSUE TITLE
Impossible to use with Uno / Wasm due to missing UnmanagedCallersOnly attributes

### ISSUE THREAD

**Issue by theCapypara** [NLua/NLua#440]
Hi!
I'm no expert in C# / .NET so I'm not actually sure where this requirement exactly comes from, but when trying to use NLua with uno.wasm.bootstrap to get C# code compiled to Web Assembly this library is fully incompatible at the moment:

```
error: System.PlatformNotSupportedException: No native to managed transition for method 'int NLua.MetaFunctions:CollectObject (intptr)', missing [UnmanagedCallersOnly] attribute.
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate[LuaFunction](LuaFunction d)
   at KeraLua.DelegateExtensions.ToFunctionPointer(LuaFunction d)
   at KeraLua.Lua.PushCClosure(LuaFunction function, Int32 n)
```

This concrete stacktrace is from an older version, but I also tried the newest, and it's the same behaviour.
Simply adding this attribute isn't an option, since [UnmanagedCallersOnly](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute?view=net-5.0) can not be used with function delegates, so I'm pretty much stuck here.

**Comment by viniciusjarina** [comment]
Well . if FNA is running on WebAssembly that means they are able to P/Invoke SDL, should be easy to use the same approach.

One alternative is to use [MoonSharp](https://github.com/moonsharp-devs/moonsharp) which doesn't do any P/invoke, it's a 100% managed.
