### ISSUE TITLE
AccessViolationException 

### ISSUE THREAD

**Issue by lee8871** [NLua/NLua#486]
Hi
I have a .netframework process using Nlua. It throws a System.AccessViolationException At:
``` C#
main_lua.DoString(lua_str); //now lua_str is "randomDelaySendOnce(14, 861)"
```
Usualy, this code works well. It throws the exception if running fast. (about 10 calling each second, may throw in 1000 calls.) 

```
   at KeraLua.NativeMethods.luaL_loadbufferx(IntPtr luaState, Byte[] buff, UIntPtr sz, String name, String mode)
   at KeraLua.Lua.LoadBuffer(Byte[] buffer, String name, String mode)
   at KeraLua.Lua.LoadString(String chunk, String name)
   at NLua.Lua.DoString(String chunk, String chunkName)
   at ChholConfig.LuaThread.<>c__DisplayClass18_0.<doLua>b__0() in D:\L\Cs\ChholConfig\ChholConfig\LuaCmd\LuaThread.cs:line 41
   at ChholConfig.LuaThread.<>c__DisplayClass19_0.<run>g__a|0() in D:\L\Cs\ChholConfig\ChholConfig\LuaCmd\LuaThread.cs:line 44
   at ChholConfig.LuaThread.loopThread() in D:\L\Cs\ChholConfig\ChholConfig\LuaCmd\LuaThread.cs:line 75
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
All lua string is worked in a C# thread. There is a queue keep all lua actions, a thread create lua, and run all actions in a loop.
``` C#
  		public void loopThread() {
			main_lua = new Lua();
			main_lua.State.Encoding = Encoding.UTF8;
			try {
				foreach (string s in lua_reg_func) {
					main_lua.RegisterFunction(s, this, this.GetType().GetMethod(s));
				}
			} catch (Exception e) {
				Lua_log.LogLine($"Error: When initialization \n{e.Message}");
			}
			doLua(Properties.Resources.CommonInit);
			while (true) {
				if (thread_exit) {
					return;
				}
				Action a;
				lock (action_queue) {
					if (action_queue.Count == 0) {
						a = null;
					} else {
						a = action_queue.Dequeue();
					}
				}
				if (a != null) {
					a();
				} else {
					action_enqueue.WaitOne();
				}
			}
		}
```
Is there something issues? 
Thanks a lot.

**Comment by lee8871** [comment]
Ok, I am sure I have never run lua string out the thread, but create table by` lua.NewTable(table_name);`somewhere.

A hahaha. So, make sure all operation on lua object in a singo thread.
