### ISSUE TITLE
Error while trying to connect WebClient to Lua

### ISSUE THREAD

**Issue by corruptedbyte** [NLua/NLua#513]
```csharp
using NLua;
using System;
using System.IO;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Text;

namespace Asbestos
{
    internal class Program
    {
        static void Main()
        {
            Lua state = new Lua();
            state.State.Encoding = Encoding.UTF8;
            state.LoadCLRPackage();
            state.DoString(File.ReadAllText("script.lua"));
        }
    }
}```

LUA:
```lua
import('System.Web')

client = WebClient()```

Error:
```
Unhandled Exception: NLua.Exceptions.LuaScriptException: [string "chunk"]:3: attempt to call a nil value (global 'WebClient')
   at NLua.Lua.ThrowExceptionFromError(Int32 oldTop)
   at NLua.Lua.DoString(String chunk, String chunkName)
   at Asbestos.Program.Main() in D:\Dev\Sharp\Asbestos\Asbestos\Program.cs:line 17```

**Comment by viniciusjarina** [comment]
It works from C# side? Aren't you missing a Reference ?
